# GitHub Actions allows you to build, test, and deploy applications in your language of choice
name: Test

on:
  push:
    branches: [tests]
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
    # checkout the repo
    - name: Checkout the repo
      uses: actions/checkout@v1

    # use node.js matrix
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    # install dependencies, verify and test
    - name: Clean install dependencies and test
      run: |
        yarn install
        yarn run verify
        yarn run test
      env:
        CI: true
