# GitHub Actions allows you to build, test, and deploy applications in your language of choice
name: Test CI

on:
  push:
    branches: [tests]
  schedule:
  - cron: 0 10 * * SAT

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        node_version: [12.x]

    runs-on: ${{ matrix.os }}

    steps:
    # checkout the repo
    - name: Checkout the repo
      uses: actions/checkout@v2

    # use node.js matrix
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node_version }}

    # install dependencies
    - name: Clean install dependencies
      run: yarn install

    # verify build tools
    - name: Verify build tools
      run: yarn run verify

    # test proccess
    - name: Test proccess
      run: yarn run test
      env:
        CI: ${{ true }}
